-- BEC-149: This migration was renumbered to 008_sso to fix a duplicate prefix
-- (007_cost_rollups and 007_sso shared prefix 007).
--
-- This file is retained for git history only. The migrator skips it based on
-- the SQLITE_MIGRATION_RENAMES map in migrator.ts, which also renames any
-- existing "007_sso" entries in schema_migrations to "008_sso" so that
-- existing deployments do not re-run this migration.
--
-- Active migration: packages/core/src/db/migrations/sqlite/008_sso.sql
