-- BEC-149: This migration was renumbered to 009_review_model_runs to fix cascading
-- prefix collision introduced when 007_sso was renumbered to 008_sso.
--
-- This file is retained for git history only. The migrator skips it based on
-- the SQLITE_MIGRATION_RENAMES map in migrator.ts, which also renames any
-- existing "008_review_model_runs" entries in schema_migrations to
-- "009_review_model_runs" so that existing deployments do not re-run this migration.
--
-- Active migration: packages/core/src/db/migrations/sqlite/009_review_model_runs.sql
