-- BEC-149: This migration was renumbered to 011_qa_run_columns to fix cascading
-- prefix collision introduced when 007_sso was renumbered to 008_sso.
--
-- This file is retained for git history only. The migrator skips it based on
-- the SQLITE_MIGRATION_RENAMES map in migrator.ts, which also renames any
-- existing "010_qa_run_columns" entries in schema_migrations to
-- "011_qa_run_columns" so that existing deployments do not re-run this migration.
--
-- Active migration: packages/core/src/db/migrations/sqlite/011_qa_run_columns.sql
