-- BEC-149: This migration was renumbered to 014_missing_indexes to fix a
-- duplicate prefix (013_missing_indexes and 013_triage_results shared
-- prefix 013).
--
-- This file is retained for git history only. The migrator skips it based on
-- the SQLITE_MIGRATION_RENAMES map in migrator.ts, which also renames any
-- existing "013_missing_indexes" entries in schema_migrations to
-- "014_missing_indexes" so existing deployments do not re-run this migration.
--
-- Active migration: packages/core/src/db/migrations/sqlite/014_missing_indexes.sql
