-- BEC-149: This migration was renumbered to 009_sso to fix a duplicate prefix
-- (008_cost_rollups and 008_sso shared prefix 008).
--
-- This file is retained for git history only. The migrator skips it based on
-- the POSTGRES_MIGRATION_RENAMES map in migrator.ts, which also renames any
-- existing "008_sso" entries in schema_migrations to "009_sso" so that
-- existing deployments do not re-run this migration.
--
-- Active migration: packages/core/src/db/migrations/postgres/009_sso.sql
