-- BEC-149: This migration was renumbered to 011_release_manager to fix cascading
-- prefix collision introduced when 008_sso was renumbered to 009_sso.
--
-- This file is retained for git history only. The migrator skips it based on
-- the POSTGRES_MIGRATION_RENAMES map in migrator.ts, which also renames any
-- existing "010_release_manager" entries in schema_migrations to
-- "011_release_manager" so that existing deployments do not re-run this migration.
--
-- Active migration: packages/core/src/db/migrations/postgres/011_release_manager.sql
