-- BEC-149: This file has been renamed to 013_qa_gap_issues.sql to fix a duplicate numeric prefix.
-- Kept as a no-op placeholder so existing schema_migrations records are not affected
-- (the migrator's POSTGRES_MIGRATION_RENAMES map handles the rename on startup).
