-- BEC-149: This migration was renumbered to 014_stage_runs_cache_tokens to fix
-- a duplicate prefix (013_qa_gap_issues and 013_stage_runs_cache_tokens shared
-- prefix 013 after the initial BEC-149 rename pass).
--
-- This file is retained for git history only. The migrator skips it based on
-- the POSTGRES_MIGRATION_RENAMES map in migrator.ts, which also renames any
-- existing "013_stage_runs_cache_tokens" entries in schema_migrations to
-- "014_stage_runs_cache_tokens" so existing deployments do not re-run this
-- migration.
--
-- Active migration: packages/core/src/db/migrations/postgres/014_stage_runs_cache_tokens.sql
